SET IDENTITY_INSERT [dbo].[StateProvince] ON
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (1, 1, N'AA (Armed Forces Americas)', N'AA', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (2, 1, N'AE (Armed Forces Europe)', N'AE', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (3, 1, N'Alabama', N'AL', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (4, 1, N'Alaska', N'AK', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (5, 1, N'American Samoa', N'AS', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (6, 1, N'AP (Armed Forces Pacific)', N'AP', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (7, 1, N'Arizona', N'AZ', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (8, 1, N'Arkansas', N'AR', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (9, 1, N'California', N'CA', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (10, 1, N'Colorado', N'CO', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (11, 1, N'Connecticut', N'CT', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (12, 1, N'Delaware', N'DE', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (13, 1, N'District of Columbia', N'DC', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (14, 1, N'Federated States of Micronesia', N'FM', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (15, 1, N'Florida', N'FL', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (16, 1, N'Georgia', N'GA', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (17, 1, N'Guam', N'GU', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (18, 1, N'Hawaii', N'HI', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (19, 1, N'Idaho', N'ID', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (20, 1, N'Illinois', N'IL', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (21, 1, N'Indiana', N'IN', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (22, 1, N'Iowa', N'IA', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (23, 1, N'Kansas', N'KS', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (24, 1, N'Kentucky', N'KY', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (25, 1, N'Louisiana', N'LA', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (26, 1, N'Maine', N'ME', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (27, 1, N'Marshall Islands', N'MH', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (28, 1, N'Maryland', N'MD', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (29, 1, N'Massachusetts', N'MA', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (30, 1, N'Michigan', N'MI', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (31, 1, N'Minnesota', N'MN', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (32, 1, N'Mississippi', N'MS', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (33, 1, N'Missouri', N'MO', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (34, 1, N'Montana', N'MT', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (35, 1, N'Nebraska', N'NE', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (36, 1, N'Nevada', N'NV', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (37, 1, N'New Hampshire', N'NH', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (38, 1, N'New Jersey', N'NJ', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (39, 1, N'New Mexico', N'NM', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (40, 1, N'New York', N'NY', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (41, 1, N'North Carolina', N'NC', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (42, 1, N'North Dakota', N'ND', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (43, 1, N'Northern Mariana Islands', N'MP', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (44, 1, N'Ohio', N'OH', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (45, 1, N'Oklahoma', N'OK', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (46, 1, N'Oregon', N'OR', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (47, 1, N'Palau', N'PW', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (48, 1, N'Pennsylvania', N'PA', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (49, 1, N'Puerto Rico', N'PR', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (50, 1, N'Rhode Island', N'RI', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (51, 1, N'South Carolina', N'SC', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (52, 1, N'South Dakota', N'SD', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (53, 1, N'Tennessee', N'TN', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (54, 1, N'Texas', N'TX', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (55, 1, N'Utah', N'UT', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (56, 1, N'Vermont', N'VT', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (57, 1, N'Virgin Islands', N'VI', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (58, 1, N'Virginia', N'VA', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (59, 1, N'Washington', N'WA', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (60, 1, N'West Virginia', N'WV', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (61, 1, N'Wisconsin', N'WI', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (62, 1, N'Wyoming', N'WY', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (63, 2, N'Alberta', N'AB', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (64, 2, N'British Columbia', N'BC', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (65, 2, N'Manitoba', N'MB', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (66, 2, N'New Brunswick', N'NB', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (67, 2, N'Newfoundland and Labrador', N'NL', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (68, 2, N'Northwest Territories', N'NT', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (69, 2, N'Nova Scotia', N'NS', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (70, 2, N'Nunavut', N'NU', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (71, 2, N'Ontario', N'ON', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (72, 2, N'Prince Edward Island', N'PE', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (73, 2, N'Quebec', N'QC', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (74, 2, N'Saskatchewan', N'SK', 1, 1)
INSERT [dbo].[StateProvince] ([Id], [CountryId], [Name], [Abbreviation], [Published], [DisplayOrder]) VALUES (75, 2, N'Yukon Territory', N'YU', 1, 1)
SET IDENTITY_INSERT [dbo].[StateProvince] OFF